# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Synchronize all development"
  lane :sync_all_dev do
    # Uncomment the following line if you want to register a new Apple device on the developer portal
    # sync_device_info
    match(type: "development")
  end

  desc "Synchronize all appstore certificates"
  lane :sync_all_appstore_certs do
    match(type: "appstore")
  end

  desc "Register new devices"
  lane :sync_device_info do
    register_devices(
      devices: {
        # Uncomment the line below this comment if you want to register a new Apple device on the developer portal
        # If having to trouble finding the device UUID, find more information here: https://developer.apple.com/documentation/xcode/distributing-your-app-to-registered-devices
        
        # "Device Name" => " Device UUID",
      }
    )
  end


  lane :beta do
    sync_code_signing(
      type: "appstore",
      readonly: true,
      app_identifier: "app.facethefacts",
      verbose: true,
      git_basic_authorization: Base64.strict_encode64(ENV["MATCH_GIT_BASIC_AUTHORIZATION"])
    )
    build_ios_app(
      workspace: "FaceTheFacts.xcworkspace",
      scheme: "FaceTheFacts",
      export_method: "app-store",
      silent: true,
      clean: true
    )        
    upload_to_testflight(
      api_key_path("fastlane/AppStoreConnectAPIKey.json"),
      skip_waiting_for_build_processing: true,
      skip_submission: true)
  end

  lane :production do
    setup_ci
    app_store_connect_api_key(
      is_key_content_base64: true,
      in_house: false,
      )
    deliver(
      submit_for_review: false,
      skip_binary_upload: true,
      run_precheck_before_submit: false,
      automatic_release: true,
      force: true
    )       
    
  end

end