# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:android)

platform :android do

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Run gradle linting"
  lane :lint do
    gradle(task: "lint")
    sh("cat", "../app/build/reports/lint-results.xml")
  end

  lane :version_code do
    path = '../app/build.gradle'
    re = /versionCode\s+(\d+)/ 
  
    s = File.read(path)
    versionCode = s[re, 1].to_i
    s[re, 1] = (versionCode + 1).to_s
  
    f = File.new(path, 'w')
    f.write(s)
    f.close
  end

  desc 'Deploy to play store'
  lane :production do
    gradle(task: 'clean bundleRelease')
    upload_to_play_store(
      track: 'production',
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_screenshots: true,
      skip_upload_images: true,
      skip_upload_apk: true
    )
  end

  lane :alpha do
    gradle(task: 'clean bundleRelease')
    upload_to_play_store(
      track: 'alpha',
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_screenshots: true,
      skip_upload_images: true,
      skip_upload_aab: true,
      skip_upload_apk: false,
    )
  end
end
