on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.x"

      - name: Build install
        run: cd android && bundle install

      - name: Install packages
        run: yarn install

      - name: ESLint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          eslint_flags: '. --ext .js,.jsx,.ts,.tsx'

      - name: Run javascript tests
        run: npm run test

  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    if: ${{ github.event_name == 'push' }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.x"

      - name: Build install
        run: cd android && bundle install

      - name: Install packages
        run: yarn install

      - name: Decrypt keystore
        run: |
          cd android/app
          echo ${{ secrets.KEYSTORE_BASE_64 }} | base64 --decode > face-the-facts.keystore

      - name: Decrypt service-account
        run: |
          cd android
          echo ${{ secrets.SERVICE_ACCOUNT_JSON }} | base64 --decode > service-account.json

      - name: Create android/gradle.properties
        run: |
          cd android
          echo "storeFile=${{ secrets.KEYSTORE_FILE }}" >> key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> key.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> key.properties

      - name: Create data.json mock
        run: echo "[]" >> data.json

      - name: Deploy alpha to Google Playstore
        run: |
          cd android
          fastlane alpha
