name: ci-cd

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  deployment_ios:
    runs-on: macos-latest
    if: ${{ github.event_name == 'push' }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Match Repo Clone Test (please delete this)
        env:
          GIT_SSH_COMMAND: 'ssh -o StrictHostKeyChecking=no'
        run: |
          eval "$(ssh-agent -s)"
          ssh-add -<<< "${{ secrets.MATCH_DEPLOY_KEY }}"
          git clone git@github.com:FaceTheFacts/fastlane-ios.git
          ls fastlane-ios

      - name: Install packages
        run: yarn install

      - name: Create env.json
        run: echo {'"BASE_URL"':'"${{ secrets.BASE_URL }}"', '"SENTRY_DSN"':'"${{ secrets.SENTRY_DSN }}"', '"SCAN_DATA_URL"':'"${{ secrets.SCAN_DATA_URL }}"', '"APPLE_ACCOUNT"':'"${{ secrets.APPLE_ACCOUNT }}"', '"ITC_TEAM_ID"':'"${{ secrets.ITC_TEAM_ID }}"', '"TEAM_ID"':'"${{ secrets.TEAM_ID }}"'} >> env.json

      - name: Create ios/fastlane/.env.default
        run: |
          cd ios/fastlane
          echo {APP_STORE_CONNECT_API_KEY_KEY_ID='"${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}"'} >> .env.default
          echo {APP_STORE_CONNECT_API_KEY_ISSUER_ID='"${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}"'} >> .env.default
          echo {APP_STORE_CONNECT_API_KEY_KEY='"${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}"'} >> .env.default
          echo {MATCH_DEPLOY_KEY='"${{ secrets.MATCH_DEPLOY_KEY }}"'} >> .env.default

      - name: Create ios/fastlane/AppStoreConnectAPIKey.json
        run: |
          cd ios/fastlane
          echo {'"key_id"':'"${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}"'} >> AppStoreConnectAPIKey.json 
          echo {'"issuer_id"':'"${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}"'} >> AppStoreConnectAPIKey.json
          echo {'"key"':'"${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}"'} >> AppStoreConnectAPIKey.json

      - name: Test ci plugin
        run: |
          cd ios
          bundle exec fastlane init_ci

  deployment_android:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Build install
        run: cd android && bundle install

      - name: Install packages
        run: yarn install

      - name: Decrypt keystore
        run: |
          cd android/app
          echo ${{ secrets.KEYSTORE_BASE_64 }} | base64 --decode > face-the-facts.keystore

      - name: Decrypt service-account
        run: |
          cd android
          echo ${{ secrets.SERVICE_ACCOUNT_JSON }} | base64 --decode > service-account.json

      - name: Create android/gradle.properties
        run: |
          cd android
          echo "storeFile=${{ secrets.KEYSTORE_FILE }}" >> key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> key.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> key.properties

      - name: Create android/sentry.properties
        run: |
          cd android
          echo "defaults.url=${{secrets.SENTRY_URL}}" >> sentry.properties
          echo "defaults.org={{secrets.SENTRY_ORG}}" >> sentry.properties
          echo "defaults.project={{secrets.SENTRY_PROJ}}" >> sentry.properties
          echo "auth.token={{secrets.SENTRY_TOKEN}}" >> sentry.properties

      - name: Create data.json mock
        run: echo "[]" >> data.json

      - name: Create env.json
        run: echo {'"BASE_URL"':'"${{ secrets.BASE_URL }}"', '"SENTRY_DSN"':'"${{ secrets.SENTRY_DSN }}"', '"SCAN_DATA_URL"':'"${{ secrets.SCAN_DATA_URL }}"', '"APPLE_ACCOUNT"':'"${{ secrets.APPLE_ACCOUNT }}"', '"ITC_TEAM_ID"':'"${{ secrets.ITC_TEAM_ID }}"', '"TEAM_ID"':'"${{ secrets.TEAM_ID }}"'} >> env.json

      - name: Deploy alpha to Google Playstore
        run: |
          cd android
          bundle exec fastlane alpha
