name: ci-cd

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'

      - name: Install packages
        run: yarn install

      - name: Run javascript tests
        run: npm run test

  deployment:
    runs-on: ubuntu-latest
    needs: [eslint, testing]
    if: ${{ github.event_name == 'push' }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'

      - name: Build install
        run: cd android && bundle install

      - name: Install packages
        run: yarn install

      - name: Decrypt keystore
        run: |
          cd android/app
          echo ${{ secrets.KEYSTORE_BASE_64 }} | base64 --decode > face-the-facts.keystore

      - name: Decrypt service-account
        run: |
          cd android
          echo ${{ secrets.SERVICE_ACCOUNT_JSON }} | base64 --decode > service-account.json

      - name: Create android/gradle.properties
        run: |
          cd android
          echo "storeFile=${{ secrets.KEYSTORE_FILE }}" >> key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> key.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> key.properties

      - name: Create env.json
        run: echo {'"BASE_URL"':'"${{ secrets.BASE_URL }}"', '"SENTRY_DSN"':'"${{ secrets.SENTRY_DSN }}"', '"SCAN_DATA_URL"':'"${{ secrets.SCAN_DATA_URL }}"', '"APPLE_ACCOUNT"':'"${{ secrets.APPLE_ACCOUNT }}"', '"ITC_TEAM_ID"':'"${{ secrets.ITC_TEAM_ID }}"', '"TEAM_ID"':'"${{ secrets.TEAM_ID }}"'} >> env.json

      - name: Create android/sentry.properties
        run: |
          cd android
          echo "defaults.url=${{secrets.SENTRY_URL}}" >> sentry.properties
          echo "defaults.org={{secrets.SENTRY_ORG}}" >> sentry.properties
          echo "defaults.project={{secrets.SENTRY_PROJ}}" >> sentry.properties
          echo "auth.token={{secrets.SENTRY_TOKEN}}" >> sentry.properties

      - name: Create data.json mock
        run: echo "[]" >> data.json

      - name: Deploy alpha to Google Playstore
        run: |
          cd android
          fastlane alpha

      - name: Deploy alpha to Apple Appstore
        run: |
          cd ios
          fastlane beta
